# renv scans this file for packages used by the Quarto rendering toolchain.
if (FALSE) {
  library(cmapr)
  library(digest)
  library(foundryR)
  library(htmltools)
  library(httr2)
  library(huggingfaceR)
  library(irr)
  library(jsonlite)
  library(knitr)
  library(onet2r)
  library(png)
  library(readr)
  library(rmarkdown)
  library(rvest)
  library(stringi)
  library(stringr)
  library(tesseract)
}
